// <auto-generated />
namespace MobileApp.Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Auction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Auction));
        
        string IMigrationMetadata.Id
        {
            get { return "201909271123253_Auction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
